### ISSUE TITLE
Doesn't work with Ubuntu 20.04

### ISSUE THREAD

**Issue by ae4ml** [icamys/locindicator#2]
I have a similar program running on an old laptop with 16.04 . Really miss this on 20.04

**Comment by icamys** [comment]
@ae4ml I figured out why it could not work. The reason was that if you run the bootstrap script on behalf of the root, the indicator won't display, because you are probably running your graphical interface on behalf of another user. I just found this possible bug and change the installation instructions. Now the docs are more clear and it 100% works on Ubuntu 20.04 (I checked it personally). If anyone reading this thread will face the issue again, please feel free to open a new issue.
